db_path = "postgresql://apato:apato@localhost:5432/postgres"
telegram_bot_token = "xxx"
consumer_timeout_seconds = 60
producer_timeout_seconds = 60
consumer_thread_limit = 5

# Calculation assumptions
loan_duration_years = 25
down_payment_percentage = 20
avg_vacant_month_per_year = 1
avg_estimated_rent_increase_per_year = 1
estimated_yearly_apartment_price_increase = 1
avg_renovation_costs = 5000
tax = 30

# Optional ML service endpoint (set to null or omit to use heuristic fallback)
ml_service_url = "http://localhost:8000"

# Optional HTTP API bind address (default 0.0.0.0:8080)
http_bind_address = "0.0.0.0:8080"
